### ISSUE TITLE
A typo for writing adjoint source in ASDF format

### ISSUE THREAD

**Issue by ziyixi** [krischer/pyadjoint#5]
https://github.com/krischer/pyadjoint/blob/e42f24acd46a981b85a57ca4039313e1886f1223/src/pyadjoint/adjoint_source.py#L190

Hi Lion,
It seems that this line should be changed to `specfem_adj_source[:, 0] += time_offset `.

**Comment by krischer** [comment]
You are of course right. Fixed in 8a20e47bdd2796ff1e8266cf5a9d2fce8e084e9a

Thanks for reporting!
